### ISSUE TITLE
Missing a training pipeline?

### ISSUE THREAD

**Issue by FransHk** [farewellthree/STAN#9]
Is there still a training pipeline (example) coming as mentioned in the readme? Would be very much appreciated as it is currently quite unclear in which way the data should be presented. Thanks.

**Comment by Arsiuuu** [comment]
Have you solved it?🤩

**Comment by FransHk** [comment]
Sadly, no. No training pipeline as of yet..

**Comment by farewellthree** [comment]
hi, the training pipeline has been released now.
